name: OpenTelemetry Distribution Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Optional) clean go module cache in case previous runs left bad state
      - name: Clean Go mod cache (defensive)
        run: |
          sudo rm -rf /usr/local/go 2>/dev/null || true
          go version || true
          go clean -cache -modcache || true

      # Build with the OTel Distro Builder action
      - uses: observiq/otel-distro-builder@v1
        with:
          manifest: "./manifest.yaml"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/artifacts/*
