name: OpenTelemetry Distribution Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24
      env:
        GOPROXY: https://proxy.golang.org,direct
        GOSUMDB: sum.golang.org

    steps:
      - uses: actions/checkout@v4

      - name: Clean module cache
        run: |
          go version
          go env
          go clean -cache -modcache

      - name: Build OTel Distribution
        uses: observiq/otel-distro-builder@v1
        with:
          manifest: "./manifest.yaml"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/artifacts/*
